<?php

declare(strict_types=1);

namespace ZaberDev\Cooldown\Exceptions;

use Exception;

/**
 * Base exception class for all errors generated by the ZaberDev Cooldown package.
 */
class CooldownException extends Exception
{
}
