name: Update Packagist

on:
  push:
    branches: [ "main", "master" ]
  release:
    types: [published]

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    if: "${{ secrets.PACKAGIST_API_TOKEN != '' }}"
    steps:
      - name: Trigger Packagist Update
        run: |
          curl -XPOST -H "Content-Type: application/json" \
               "https://packagist.org/api/update-package?username=zaber-dev&apiToken=${{ secrets.PACKAGIST_API_TOKEN }}" \
               -d '{"repository":{"url":"https://packagist.org/packages/zaber-dev/laravel-cooldown"}}'
